export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY';
export const GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL';
export const GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID';
export const GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET';
export const API_SEND_MAIL_KEY = 'API_SEND_MAIL_KEY';
export const PORT = 'PORT';
export const DOMAINNAME = 'DOMAINNAME';
export const OVERRIDE_METHOD_METADATA = 'OVERRIDE_METHOD_METADATA';
export const REDIRECTPAGE = 'REDIRECTPAGE';

// Database connection constants
export const MYSQL_HOST = 'MYSQL_HOST';
export const MYSQL_PORT = 'MYSQL_PORT';
export const MYSQL_DATABASE = 'MYSQL_DATABASE';
export const MYSQL_USER = 'MYSQL_USER';
export const MYSQL_PASSWORD = 'MYSQL_PASSWORD';
