import {
  JWT_SECRET_KEY,
  JWT_REFRESH_SECRET_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CALLBACK_URL,
  API_SEND_MAIL_KEY,
  REDIRECTPAGE,
} from '../constant';

export default () => ({
  [JWT_SECRET_KEY]: process.env[JWT_SECRET_KEY],
  [JWT_REFRESH_SECRET_KEY]: process.env[JWT_REFRESH_SECRET_KEY],
  [GOOGLE_CLIENT_ID]: process.env[GOOGLE_CLIENT_ID],
  [GOOGLE_CLIENT_SECRET]: process.env[GOOGLE_CLIENT_SECRET],
  [GOOGLE_CALLBACK_URL]: process.env[GOOGLE_CALLBACK_URL],
  [API_SEND_MAIL_KEY]: process.env[API_SEND_MAIL_KEY],
  [REDIRECTPAGE]: process.env[REDIRECTPAGE],
});
